sudo: required
services:
    -docker

before_install:
    - docker build -t preethamsowkar/docker-react -f Dockerfile.dev .

scripts:
    - docker run -e CI=true preethamsowkar/docker-react npm run test